# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QuickShadow
                                 A QGIS plugin
 This plugin creates shadows from Polygons, simulating cast shadows
 based on building height, shadow angle, and a length factor (sun altitude).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-05
        copyright            : (C) 2025 by Julian Lindner
        email                : QuickShadowjulianlindner.de
 ***************************************************************************/

/***************************************************************************
 * *
 * This program is free software; you can redistribute it and/or modify  *
 * it under the terms of the GNU General Public License as published by  *
 * the Free Software Foundation; either version 2 of the License, or     *
 * (at your option) any later version.                                   *
 * *
 ***************************************************************************/
"""

__author__ = 'Julian Lindner'
__date__ = '2025-12-05'
__copyright__ = '(C) 2025 by Julian Lindner'

# This will get replaced with a git SHA1 when you do a git archive
__revision__ = '$Format:%H$'

import processing

from qgis.PyQt import QtGui
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterField,
                       QgsApplication,
                       QgsProcessingUtils,
                       QgsProcessingParameterBoolean,
                       # Import QgsVectorLayer for resolving temporary layers by ID
                       QgsVectorLayer)
from qgis import utils


class QuickShadowAlgorithm(QgsProcessingAlgorithm):
    """
    QGIS Processing algorithm to generate shadow polygons from input building polygons.
    It supports calculating simple ground shadows and optional complex cast shadows
    on other, lower buildings.
    """

    # Constants (Parameter Definitions)
    INPUT = 'INPUT'
    OUTPUT = 'OUTPUT'
    HEIGHT_DIFFERENCE_OUTPUT = 'HEIGHT_DIFFERENCE_OUTPUT'
    DEFAULT_HEIGHT_FIELD_NAME = 'default_height_value'
    HEIGHT_FIELD = 'HEIGHT_FIELD'
    SHADOW_ANGLE = 'SHADOW_ANGLE' 
    SHADOW_LENGTH_FACTOR = 'SHADOW_LENGTH_FACTOR'
    HEIGHT_DIFFERENCE_FIELD = 'HEIGHT_DIFF'
    RUN_HEIGHT_DIFFERENCE = 'RUN_HEIGHT_DIFFERENCE'

    def initAlgorithm(self, config):
        """
        Defines the inputs and outputs (parameters) of the algorithm.
        """

        # Add Input Layer. Must be a Vector Polygon Layer (e.g., buildings).
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        # Parameter for the field containing the building height or level value.
        self.addParameter(
            QgsProcessingParameterField(
                self.HEIGHT_FIELD,
                self.tr('Height Field'),
                parentLayerParameterName=self.INPUT,
                optional=True, 
                defaultValue=self.DEFAULT_HEIGHT_FIELD_NAME, # Placeholder for 'no selection'
                type=QgsProcessingParameterField.Any
            )
        )

        # Parameter for the direction of the shadow, measured in degrees clockwise from North (0-360).
        self.addParameter(
            QgsProcessingParameterNumber(
                self.SHADOW_ANGLE,
                self.tr('Shadow Angle'),
                defaultValue=225.0,  # Default to Northwest (a common solar angle)
                minValue=0.0,
                maxValue=360.0
            )
        )
        
        # Parameter for the shadow length factor. 
        # Length = Height * Factor. A value of 1.0 means a 45-degree sun altitude (tan(45)=1).
        self.addParameter(
            QgsProcessingParameterNumber(
                self.SHADOW_LENGTH_FACTOR,
                self.tr('Shadow Length / Factor'),
                defaultValue=1.0,  
                minValue=0.1,      # Constraint to avoid near-zero length
            )
        )

        # Define the main output sink for the generated ground shadows.
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Ground Shadows')
            )
        )

        # Boolean parameter to enable or disable the complex calculation for cast shadows on other objects.
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.RUN_HEIGHT_DIFFERENCE,
                self.tr('Calculate Cast Shadows on other objects (computationally intensive)'),
                defaultValue=False
            )
        )

        # Define the optional secondary output sink for the filtered cast shadows (shadows on lower buildings).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.HEIGHT_DIFFERENCE_OUTPUT,
                self.tr('Shadows on Lower Buildings'),
                optional=True
            )
        )

# ----------------------------------------------------------------------
## Helper Methods for Process Algorithm
# ----------------------------------------------------------------------

    def _get_height_expression(self, parameters, context, feedback):
        """
        Determines the QGIS expression string for the building height value.
        It uses the selected field name or a default value of 1.0 if no field is specified.
        
        :param parameters: The algorithm's parameter dictionary.
        :param context: The QGIS Processing context.
        :param feedback: The feedback object for reporting progress/errors.
        :return: A string containing the QGIS expression for the height value.
        """
        height_field_name = self.parameterAsString(parameters, self.HEIGHT_FIELD, context)
        
        # Check if Height Field is filled out and is not the default placeholder
        if height_field_name and height_field_name != self.DEFAULT_HEIGHT_FIELD_NAME:
            # Enclose the field name in double quotes for safe expression usage
            height_value_expression = f"\"{height_field_name}\""
            feedback.pushInfo(f"Using field: {height_field_name} for shadow calculation.")
        else:
            # Use a default height of 1.0 for calculation if no field is provided
            height_value_expression = "1.0"
            feedback.pushInfo("No height field selected. Using a default height value of 1.0.")
            
        return height_value_expression

    def _run_geometry_by_expression(self, parameters, context, feedback, height_value_expression):
        """
        Constructs and executes the QGIS 'qgis:geometrybyexpression' algorithm 
        to create the raw shadow polygons.
        The shadow is calculated by extruding the polygon's line segments 
        based on the height, factor, and angle.
        
        :param parameters: The algorithm's parameter dictionary.
        :param context: The QGIS Processing context.
        :param feedback: The feedback object for reporting progress/errors.
        :param height_value_expression: The QGIS expression for the height of the caster.
        :return: The ID of the temporary result layer (raw shadows) or None on failure.
        """
        shadow_angle = self.parameterAsDouble(parameters, self.SHADOW_ANGLE, context)
        shadow_factor = self.parameterAsDouble(parameters, self.SHADOW_LENGTH_FACTOR, context)

        # Calculate x and y offset (projection) from angle and factor
        # Logic: offset = - (height * factor) * trigonometric_function(angle)
        # The negative sign flips the direction from sun angle (caster) to shadow extension (receiver)
        # QGIS trigonometry functions use radians.
        dx = f"-( {height_value_expression} * {shadow_factor}) * sin(radians({shadow_angle}))"
        dy = f"-( {height_value_expression} * {shadow_factor}) * cos(radians({shadow_angle}))"

        # Define the QGIS Geometry Expression:
        # 1. segments_to_lines(@geometry): Converts the building polygon to its constituent line segments.
        # 2. extrude(..., dx, dy): Extrudes each segment by the calculated x and y offset.
        # 3. buffer(..., 0): Creates a zero-width buffer to convert the extruded geometry (a multi-line/surface)
        #    into a valid polygon, effectively closing the shadow boundary.
        expression = f"""
            buffer( 
                extrude(
                    segments_to_lines(@geometry), 
                    {dx}, 
                    {dy}
                ),
                0
            )
        """
              
        # Define the parameters for the 'Geometry by Expression' algorithm
        alg_params = {
            'INPUT': parameters[self.INPUT],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
            'EXPRESSION': expression,
            # Output type is Polygon
            'OUTPUT_GEOMETRY': QgsProcessing.TypeVectorPolygon
        }
        
        feedback.pushInfo(f"Executing Geometry by Expression with:\nExpression: {expression}")
        
        # Execute the built-in QGIS processing algorithm
        result_tuple = QgsApplication.processingRegistry().algorithmById('qgis:geometrybyexpression').run(
           alg_params,
           context,
           feedback
        )  
        
        # Check for execution success
        if result_tuple is None or 'OUTPUT' not in result_tuple[0]:
            feedback.reportError("Failed to execute 'Geometry by Expression' algorithm.", True)
            return None
        
        # Return the ID of the temporary output layer
        return result_tuple[0]['OUTPUT']


    def _post_process_layer(self, parameters, context, feedback, output_layer):
        """
        Applies a basic grey symbology to the output layer for visual representation.
        
        :param parameters: The algorithm's parameter dictionary (unused, but kept for signature).
        :param context: The QGIS Processing context (unused, but kept for signature).
        :param feedback: The feedback object for reporting progress/errors (unused, but kept for signature).
        :param output_layer: The QgsVectorLayer object to be styled.
        """
        # --- 1. Apply Styling ---
        single_symbol_renderer = output_layer.renderer()
        symbol = single_symbol_renderer.symbol()
        
        # Set fill and stroke colour to a light grey for a shadow effect
        grey_color = QtGui.QColor.fromRgb(200, 200, 200)
        symbol.setColor(grey_color)
        symbol.symbolLayer(0).setStrokeColor(grey_color)
        
        # Refresh symbology in the QGIS interface (if running within QGIS GUI)
        output_layer.triggerRepaint()
        if utils.iface:
            utils.iface.layerTreeView().refreshLayerSymbology(output_layer.id())

    def _run_height_difference_calculation(self, parameters, context, feedback, shadow_layer_id):
        """
        Calculates cast shadows on lower buildings by performing:
        1. Spatial Join: Identifies overlaps between shadows (caster) and buildings (receiver).
        2. Field Calculator: Calculates the height difference (Caster Height - Receiver Height).
        3. Filter/Intersect: Isolates features where difference > 0 and clips the shadow 
           to the receiver building's geometry (i.e., shadow on top of the lower building).
           
        :param parameters: The algorithm's parameter dictionary.
        :param context: The QGIS Processing context.
        :param feedback: The feedback object for reporting progress/errors.
        :param shadow_layer_id: The ID of the raw shadow layer (output of _run_geometry_by_expression).
        :return: A tuple of (processed_shadow_layer_id, filtered_intersection_layer_id), 
                 or (raw_shadow_layer_id, None) if the height field is missing, or None on failure.
        """
        
        height_field_name = self.parameterAsString(parameters, self.HEIGHT_FIELD, context)
        
        # Pre-check: Height field must be available for height difference calculation
        if height_field_name == self.DEFAULT_HEIGHT_FIELD_NAME:
            feedback.pushWarning("Skipping height difference calculation: Requires a primary height field.")
            return shadow_layer_id, None # Return main ID and None for the secondary output
        
        # --- A. Spatial Join (Join Attributes by Location) ---
        # Joins the height attribute of any overlapping building (receiver) to the shadow feature (caster).
        feedback.pushInfo("Step A: Running Spatial Join using INPUT layer as comparison...")

        join_params = {
            'INPUT': shadow_layer_id,       # The raw shadow features (caster)
            'JOIN': parameters[self.INPUT], # The building features (receiver)
            'PREDICATE': [0],               # Only join where the shadow INTERSECTS the building
            'JOIN_FIELDS': [height_field_name], # Only join the height field
            'METHOD': 0,
            'DISCARD_NON_MATCHING': True,   # Only keep shadow features that overlap a building
            'PREFIX': 'comp_',              # Prefix for the joined field (receiver's height)
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }

        join_result = QgsApplication.processingRegistry().algorithmById('qgis:joinattributesbylocation').run(
           join_params, context, feedback
        )
        
        if join_result is None or 'OUTPUT' not in join_result[0]:
            feedback.reportError("Failed to execute Spatial Join.", True)
            return shadow_layer_id, None
            
        joined_layer_id = join_result[0]['OUTPUT']
        
        # --- B. Field Calculator ---
        # Calculate the difference: Caster_Height - Receiver_Height.
        # - The field `height_field_name` (unprefixed) is the height of the Caster building.
        # - The field `comp_height_field_name` (prefixed) is the height of the Receiver building.
        feedback.pushInfo("Step B: Calculating Height Difference (HEIGHT_DIFF)...")
        
        joined_field_name = f'comp_{height_field_name}'
        difference_expression = f"\"{height_field_name}\" - \"{joined_field_name}\""
        
        calc_params = {
            'INPUT': joined_layer_id,
            'FIELD_NAME': self.HEIGHT_DIFFERENCE_FIELD,
            'FIELD_TYPE': 0, # Float
            'FIELD_LENGTH': 10,
            'FIELD_PRECISION': 2,
            'FORMULA': difference_expression,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        
        calc_result = QgsApplication.processingRegistry().algorithmById('qgis:fieldcalculator').run(
           calc_params, context, feedback
        )
        
        if calc_result is None or 'OUTPUT' not in calc_result[0]:
            feedback.reportError("Failed to execute Field Calculator.", True)
            return shadow_layer_id, None

        calculated_layer_id = calc_result[0]['OUTPUT']
        
        # --- C. Filter and Intersect for Shadows on Lower Buildings ---
        filtered_layer_id = None
        
        # C1. Select features where HEIGHT_DIFF is greater than 0
        # This isolates the shadow features *only* where the caster building is higher than the receiver building.
        if self.parameterAsOutputLayer(parameters, self.HEIGHT_DIFFERENCE_OUTPUT, context) is not None:
            
            feedback.pushInfo("Step C1: Isolating features with a positive Height Difference...")
            
            filter_params = {
                'INPUT': calculated_layer_id,
                'EXPRESSION': f"\"{self.HEIGHT_DIFFERENCE_FIELD}\" > 0",
                'METHOD': 0, # Create subset
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            
            filter_result = QgsApplication.processingRegistry().algorithmById('qgis:selectbyexpression').run(
               filter_params, context, feedback
            )
            
            if filter_result is None or 'OUTPUT' not in filter_result[0]:
                feedback.reportError("Failed to execute Select by Expression (Filtering Caster > Receiver).", True)
                return shadow_layer_id, None
            
            filtered_features_layer_id = filter_result[0]['OUTPUT']
            
            # C2. Intersection (Clipping Shadow to Building Top)
            # This step clips the full shadow polygon (the result of C1) by the geometry of the receiver building.
            # The result is the area of the shadow that falls *on* the lower building.
            
            feedback.pushInfo("Step C2: Running Intersection (Clipping Shadow to Building Top)...")

            # --- fix 1: convert FILTERED layer properly ---
            # Resolve the temporary layer ID to a QgsMapLayer object
            filtered_layer = QgsProcessingUtils.mapLayerFromString(filtered_features_layer_id, context)
            if filtered_layer is None:
                # Fallback to creating a vector layer object if resolving by string failed
                filtered_layer = QgsVectorLayer(filtered_features_layer_id, "filtered", "ogr")

            # --- fix 2: get INPUT layer *as URI* ---
            # The Overlay layer must be the original building layer to act as the clip boundary.
            input_layer_id = parameters[self.INPUT]
            input_layer = context.getMapLayer(input_layer_id)
            if input_layer is None:
                feedback.reportError("Input layer could not be resolved for intersection.")
                return shadow_layer_id, None

            # Use the URI (source) of the original input layer
            input_uri = input_layer.source()

            intersection_params = {
                'INPUT': filtered_layer, # The filtered shadow features
                'OVERLAY': input_uri,    # The building features (clip boundary)
                'INPUT_FIELDS': [self.HEIGHT_DIFFERENCE_FIELD], # Keep the difference field
                'OVERLAY_FIELDS': [],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }

            intersection_result = QgsApplication.processingRegistry().algorithmById(
                'qgis:intersection').run(intersection_params, context, feedback)

            if intersection_result is None or 'OUTPUT' not in intersection_result[0]:
                feedback.reportError("Failed to execute Intersection (Clipping Shadow to Building Top).", True)
                return shadow_layer_id, None

            filtered_layer_id = intersection_result[0]['OUTPUT']

            
            # Return the ID of the layer with all shadows (plus height diff attribute) 
            # and the ID of the layer with only cast shadows on lower buildings.
            return calculated_layer_id, filtered_layer_id

# ----------------------------------------------------------------------
## Main Processing Method
# ----------------------------------------------------------------------

    def processAlgorithm(self, parameters, context, feedback):
        """
        Main execution method for the QuickShadow algorithm.
        
        :param parameters: The algorithm's parameter dictionary.
        :param context: The QGIS Processing context.
        :param feedback: The feedback object for reporting progress/errors.
        :return: A dictionary of output layer IDs.
        """
       
        # 1. Retrieve and validate input source layer
        source = self.parameterAsSource(parameters, self.INPUT, context)

        if source is None:
            feedback.reportError("Could not load source layer for INPUT. Please ensure a valid layer is selected.", True)
            return {} 

        # 2. Determine the height value expression (e.g., "Field_Name" or "1.0")
        height_value_expression = self._get_height_expression(parameters, context, feedback)
            
        # 3. Run the 'Geometry by Expression' processing algorithm to get raw shadows
        temp_output_id = self._run_geometry_by_expression(
            parameters, 
            context, 
            feedback, 
            height_value_expression
        )
        
        if temp_output_id is None:
            return {} # Failure occurred in the sub-algorithm

        # --- Conditional Execution: Complex Shadow Calculation ---
        run_height_diff = self.parameterAsBoolean(parameters, self.RUN_HEIGHT_DIFFERENCE, context)
        
        processed_layer_id = temp_output_id # ID for the main output
        filtered_layer_id = None           # ID for the secondary output
        
        if run_height_diff:
            feedback.pushInfo("Option 'Calculate Cast Shadows' is ON. Running height difference calculation...")
            
            # 4. Calculate Overlap, Height Difference, and perform Filtering
            processed_layer_id, filtered_layer_id = self._run_height_difference_calculation(
                parameters, 
                context, 
                feedback, 
                temp_output_id
            )
            
            if processed_layer_id is None:
                return {} # Failure in calculation step
        else:
            feedback.pushInfo("Option 'Calculate Cast Shadows' is OFF. Skipping complex intersection calculation.")
        # --- END Conditional Execution ---
        
        # 5. Handle the MAIN Output (All Shadows: Ground + Overlapping)
        temp_result_layer = context.getMapLayer(processed_layer_id)

        # Prepare the final output sink for the main layer
        (sink_main, dest_id_main) = self.parameterAsSink(parameters, self.OUTPUT,
                context, temp_result_layer.fields(), temp_result_layer.wkbType(), temp_result_layer.sourceCrs())
        
        # Copy features from the temporary layer to the main output sink
        feedback.pushInfo("Copying features to the Main Output layer...")
        features_main = temp_result_layer.getFeatures()
        
        for feature in features_main:
            sink_main.addFeature(feature, QgsFeatureSink.FastInsert)

        # Apply basic styling to the final main layer
        output_layer_main = QgsProcessingUtils.mapLayerFromString(dest_id_main, context)
        self._post_process_layer(parameters, context, feedback, output_layer_main)

        # 6. Handle the SECONDARY Output (Shadows on Lower Buildings)
        dest_id_filtered = None
        if filtered_layer_id is not None:
            filtered_temp_layer = context.getMapLayer(filtered_layer_id)
            
            # Prepare the final output sink for the filtered layer
            (sink_filtered, dest_id_filtered) = self.parameterAsSink(parameters, self.HEIGHT_DIFFERENCE_OUTPUT,
                    context, filtered_temp_layer.fields(), filtered_temp_layer.wkbType(), filtered_temp_layer.sourceCrs())
            
            # Copy features from the temporary filtered layer to the secondary output sink
            feedback.pushInfo("Copying features to the Filtered Output layer (Shadows on Lower Buildings)...")
            features_filtered = filtered_temp_layer.getFeatures()
            
            for feature in features_filtered:
                sink_filtered.addFeature(feature, QgsFeatureSink.FastInsert)
            
            # Apply distinct styling (e.g., semi-transparent red) to the filtered layer
            output_layer_filtered = QgsProcessingUtils.mapLayerFromString(dest_id_filtered, context)
            if output_layer_filtered:
                symbol = output_layer_filtered.renderer().symbol()
                red_color = QtGui.QColor.fromRgb(255, 0, 0, 100) # Semi-transparent red
                symbol.setColor(red_color)
                symbol.symbolLayer(0).setStrokeColor(red_color)
                output_layer_filtered.triggerRepaint()


        # 7. Return the final sink IDs
        return {
            self.OUTPUT: dest_id_main,
            self.HEIGHT_DIFFERENCE_OUTPUT: dest_id_filtered
        }
# ----------------------------------------------------------------------
## Metadata Methods
# ----------------------------------------------------------------------

    def name(self):
        """
        Returns the internal algorithm name (used for identifying the algorithm).
        """
        return 'Create Shadow'

    def displayName(self):
        """
        Returns the user-friendly translated algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to (e.g., 'Vector Geometry').
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to.
        """
        return 'Algorithms for Vector Polygon Layer'

    def tr(self, string):
        """
        Translates a string using QGIS's translation system.
        """
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        """
        Must return a new instance of the algorithm.
        """
        return QuickShadowAlgorithm()