# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QuickShadow
                                 A QGIS plugin
 This plugin creates shadows from Polygons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-05
        copyright            : (C) 2025 by Julian Lindner
        email                : QuickShadowjulianlindner.de
 ***************************************************************************/

/***************************************************************************
 * *
 * This program is free software; you can redistribute it and/or modify  *
 * it under the terms of the GNU General Public License as published by  *
 * the Free Software Foundation; either version 2 of the License, or     *
 * (at your option) any later version.                                   *
 * *
 ***************************************************************************/
"""

__author__ = 'Julian Lindner'
__date__ = '2025-12-05'
__copyright__ = '(C) 2025 by Julian Lindner'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import processing

from qgis.PyQt import QtGui
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterField,
                       QgsApplication,
                       QgsProcessingUtils,
                       QgsProject)
from qgis import utils


class QuickShadowAlgorithm(QgsProcessingAlgorithm):

    # Constants
    INPUT = 'INPUT'
    OUTPUT = 'OUTPUT'
    DEFAULT_HEIGHT_FIELD_NAME = 'default_height_value'
    HEIGHT_FIELD = 'HEIGHT_FIELD'
    SHADOW_ANGLE = 'SHADOW_ANGLE' 
    SHADOW_LENGTH_FACTOR = 'SHADOW_LENGTH_FACTOR'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # Add Input Layer. Must be Vector Polygon Layer.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        # Added Field of Building heights / levels as an input.
        self.addParameter(
            QgsProcessingParameterField(
                self.HEIGHT_FIELD,
                self.tr('Height Field'),
                parentLayerParameterName=self.INPUT,
                optional=True, 
                defaultValue=self.DEFAULT_HEIGHT_FIELD_NAME, 
                type=QgsProcessingParameterField.Any
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.SHADOW_ANGLE,
                self.tr('Shadow Angle'),
                defaultValue=225.0,  # Default to Northwest
                minValue=0.0,
                maxValue=360.0
            )
        )
        
        self.addParameter(
            QgsProcessingParameterNumber(
                self.SHADOW_LENGTH_FACTOR,
                self.tr('Shadow Length / Factor'),
                defaultValue=1.0,  # Default to 45 degree altitude (tan(45) = 1)
                minValue=0.1,      # Avoid extremely flat angles
            )
        )

        # Create FeatureSink for Output
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )

# ----------------------------------------------------------------------
## Helper Methods for Process Algorithm
# ----------------------------------------------------------------------

    def _get_height_expression(self, parameters, context, feedback):
        """
        Determines the QGIS expression string for the building height value.
        """
        height_field_name = self.parameterAsString(parameters, self.HEIGHT_FIELD, context)
        
        # Check if Height Field is filled out and is not the default placeholder
        if height_field_name and height_field_name != self.DEFAULT_HEIGHT_FIELD_NAME:
            height_value_expression = f"\"{height_field_name}\""
            feedback.pushInfo(f"Using field: {height_field_name} for shadow calculation.")
        else:
            # Use a default height of 1.0 for calculation if no field is provided
            height_value_expression = "1.0"
            feedback.pushInfo("No height field selected. Using a default height value of 1.0.")
            
        return height_value_expression

    def _run_geometry_by_expression(self, parameters, context, feedback, height_value_expression):
        """
        Constructs the geometry expression and executes the 'qgis:geometrybyexpression' algorithm.
        Returns the temporary result layer ID or None on failure.
        """
        shadow_angle = self.parameterAsDouble(parameters, self.SHADOW_ANGLE, context)
        shadow_factor = self.parameterAsDouble(parameters, self.SHADOW_LENGTH_FACTOR, context)

        # Calculate x and y offset from angle and factor
        # Logic: offset = - (height * factor) * trigonometric_function(angle)
        # The negative sign flips the direction from sun angle to shadow extension
        dx = f"-( {height_value_expression} * {shadow_factor}) * sin(radians({shadow_angle}))"
        dy = f"-( {height_value_expression} * {shadow_factor}) * cos(radians({shadow_angle}))"

        # Define the expression: extrude line segments and buffer by 0 to create a shadow polygon
        expression = f"""
            buffer( 
                extrude(
                    segments_to_lines(@geometry), 
                    {dx}, 
                    {dy}
                ),
                0
            )
        """
              
        # Define the parameters for the 'Geometry by Expression' algorithm
        alg_params = {
            'INPUT': parameters[self.INPUT],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
            'EXPRESSION': expression,
            # Output type is Polygon
            'OUTPUT_GEOMETRY': QgsProcessing.TypeVectorPolygon
        }
        
        feedback.pushInfo(f"Executing Geometry by Expression with:\nExpression: {expression}")
        
        # Execute the built-in QGIS processing algorithm
        result_tuple = QgsApplication.processingRegistry().algorithmById('qgis:geometrybyexpression').run(
           alg_params,
           context,
           feedback
        )  
        
        if result_tuple is None or 'OUTPUT' not in result_tuple[0]:
            feedback.reportError("Failed to execute 'Geometry by Expression' algorithm.", True)
            return None
        
        # Return the ID of the temporary output layer
        return result_tuple[0]['OUTPUT']


    def _post_process_layer(self, parameters, context, feedback, output_layer):
        """
        Applies grey styling to the shadow layer and attempts to move it 
        below the original input layer in the layer tree.
        """
        # --- 1. Apply Styling ---
        single_symbol_renderer = output_layer.renderer()
        symbol = single_symbol_renderer.symbol()
        
        # Set fill and stroke colour to a light grey
        grey_color = QtGui.QColor.fromRgb(200, 200, 200)
        symbol.setColor(grey_color)
        symbol.symbolLayer(0).setStrokeColor(grey_color)
        
        # Refresh symbology in the interface
        output_layer.triggerRepaint()
        if utils.iface:
            utils.iface.layerTreeView().refreshLayerSymbology(output_layer.id())


        # --- 2. Adjust Layer Ordering ---
        original_layer = QgsProcessingUtils.mapLayerFromString(
            parameters[self.INPUT], 
            context
        )

        if original_layer:
            root = QgsProject.instance().layerTreeRoot()
            original_layer_node = root.findLayer(original_layer.id())
            new_layer_node = root.findLayer(output_layer.id())
            
            if original_layer_node and new_layer_node:
                parent_group = original_layer_node.parent()
                
                if parent_group:
                    try:
                        # Find the index of the original layer
                        original_layer_index = parent_group.children().index(original_layer_node)
                        
                        # Remove and insert the new layer node below the original (index + 1)
                        parent_group.removeChildNode(new_layer_node)
                        parent_group.insertChildNode(
                            original_layer_index + 1, 
                            new_layer_node.clone()
                        )
                        feedback.pushInfo(f"Moved new layer '{output_layer.name()}' below '{original_layer.name()}' successfully.")

                    except ValueError:
                         feedback.pushWarning("Original layer found, but its position index could not be determined. Order not adjusted.")
                else:
                    feedback.pushWarning("Original layer node has no parent. Cannot adjust order.")
            else:
                feedback.pushWarning(f"Could not find the layer nodes in the layer tree. Order not adjusted.")
        else:
            feedback.pushWarning("Could not retrieve original input layer object. Order not adjusted.")


# ----------------------------------------------------------------------
## Main Processing Method
# ----------------------------------------------------------------------

    def processAlgorithm(self, parameters, context, feedback):
       
        # 1. Retrieve input source
        source = self.parameterAsSource(parameters, self.INPUT, context)

        if source is None:
            feedback.reportError("Could not load source layer for INPUT. Please ensure a valid layer is selected.", True)
            return {} 

        # 2. Determine the height value expression (e.g., "Field_Name" or "1.0")
        height_value_expression = self._get_height_expression(parameters, context, feedback)
            
        # 3. Run the 'Geometry by Expression' processing algorithm
        temp_output_id = self._run_geometry_by_expression(
            parameters, 
            context, 
            feedback, 
            height_value_expression
        )
        
        if temp_output_id is None:
            return {} # Failure occurred in the sub-algorithm

        # 4. Retrieve the temporary result layer
        temp_result_layer = context.getMapLayer(temp_output_id)

        if temp_result_layer is None:
            feedback.reportError("Could not retrieve temporary result layer.", True)
            return {}

        # 5. Copy features from the temporary layer to the final output sink
        # Prepare the final output sink
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, temp_result_layer.fields(), temp_result_layer.wkbType(), temp_result_layer.sourceCrs())
        
        features = temp_result_layer.getFeatures()
        feature_count = temp_result_layer.featureCount()
        total = 100.0 / feature_count if feature_count else 0
        
        # Iterate and copy features
        for current, feature in enumerate(features):
            if feedback.isCanceled():
                break
            sink.addFeature(feature, QgsFeatureSink.FastInsert)
            feedback.setProgress(int(current * total))

        output_layer = QgsProcessingUtils.mapLayerFromString(dest_id, context)
        assert output_layer is not None

        # 6. Post-process: style and order the new layer
        self._post_process_layer(parameters, context, feedback, output_layer)

        # 7. Return the final sink ID
        return {
            self.OUTPUT: dest_id 
        }

# ----------------------------------------------------------------------
## Metadata Methods
# ----------------------------------------------------------------------

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm.
        """
        return 'Create Shadow'

    def displayName(self):
        """
        Returns the translated algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to.
        """
        return 'Algorithms for Vector Polygon Layer'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return QuickShadowAlgorithm()