# -*- coding: utf-8 -*-

"""
/***************************************************************************
QuickShadow
                                 A QGIS plugin
 This plugin creates shadows from Polygons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-01-26
        copyright            : (C) 2026 by Julian Lindner
        email                : QuickShadow@julianlindner.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Julian Lindner'
__date__ = '2026-01-26'
__copyright__ = '(C) 2026 by Julian Lindner'

import os, sys, inspect
from qgis.core import QgsApplication
from .QuickShadow_provider import QuickShadowProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class QuickShadowPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = QuickShadowProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
